default:
  image: ubuntu:24.04
  #
  # This folder is cached between builds
  # http://docs.gitlab.com/ee/ci/yaml/README.html#cache
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
    - apt -y install python3-pip python-is-python3

build:
  stage: build
  script:
  - ./build.sh
  - pip3 install --find-links ./django-starcross-gallery/dist django-starcross-gallery

tests:
  stage: test
  script:
    - python3 runtests.py

