dist: focal
language: python
python:
  - "3.10"
install:
  - ./build.sh
  - pip install --find-links ./django-starcross-gallery/dist django-starcross-gallery
  - pip install coveralls
script:
  - coverage run --source=gallery runtests.py
after_success:
  - coveralls